package dev.deadc0de.cobalt;

import dev.deadc0de.cobalt.geometry.Region;
import dev.deadc0de.cobalt.graphics.SpritesRepository;

public class Text {

    private static final String SOURCE_NAME = "text";
    private static final String SPRITES_SOURCE = "/dev/deadc0de/cobalt/images/text.png";
    private static final String BACKGROUND_NAME = "text-background";
    private static final String BACKGROUND_SOURCE = "/dev/deadc0de/cobalt/images/text_background.png";

    public static void addSprites(SpritesRepository<?> spritesRepository) {
        spritesRepository.addSource(BACKGROUND_NAME, BACKGROUND_SOURCE);
        spritesRepository.addSource(SOURCE_NAME, SPRITES_SOURCE);
        spritesRepository.addSprite("A", SOURCE_NAME, new Region(0, 0, 8, 8));
        spritesRepository.addSprite("B", SOURCE_NAME, new Region(8, 0, 8, 8));
        spritesRepository.addSprite("C", SOURCE_NAME, new Region(16, 0, 8, 8));
        spritesRepository.addSprite("D", SOURCE_NAME, new Region(24, 0, 8, 8));
        spritesRepository.addSprite("E", SOURCE_NAME, new Region(32, 0, 8, 8));
        spritesRepository.addSprite("F", SOURCE_NAME, new Region(40, 0, 8, 8));
        spritesRepository.addSprite("G", SOURCE_NAME, new Region(48, 0, 8, 8));
        spritesRepository.addSprite("H", SOURCE_NAME, new Region(56, 0, 8, 8));
        spritesRepository.addSprite("I", SOURCE_NAME, new Region(64, 0, 8, 8));
        spritesRepository.addSprite("J", SOURCE_NAME, new Region(72, 0, 8, 8));
        spritesRepository.addSprite("K", SOURCE_NAME, new Region(80, 0, 8, 8));
        spritesRepository.addSprite("L", SOURCE_NAME, new Region(88, 0, 8, 8));
        spritesRepository.addSprite("M", SOURCE_NAME, new Region(96, 0, 8, 8));
        spritesRepository.addSprite("N", SOURCE_NAME, new Region(104, 0, 8, 8));
        spritesRepository.addSprite("O", SOURCE_NAME, new Region(112, 0, 8, 8));
        spritesRepository.addSprite("P", SOURCE_NAME, new Region(120, 0, 8, 8));
        spritesRepository.addSprite("Q", SOURCE_NAME, new Region(128, 0, 8, 8));
        spritesRepository.addSprite("R", SOURCE_NAME, new Region(136, 0, 8, 8));
        spritesRepository.addSprite("S", SOURCE_NAME, new Region(144, 0, 8, 8));
        spritesRepository.addSprite("T", SOURCE_NAME, new Region(152, 0, 8, 8));
        spritesRepository.addSprite("U", SOURCE_NAME, new Region(160, 0, 8, 8));
        spritesRepository.addSprite("V", SOURCE_NAME, new Region(168, 0, 8, 8));
        spritesRepository.addSprite("W", SOURCE_NAME, new Region(176, 0, 8, 8));
        spritesRepository.addSprite("X", SOURCE_NAME, new Region(184, 0, 8, 8));
        spritesRepository.addSprite("Y", SOURCE_NAME, new Region(192, 0, 8, 8));
        spritesRepository.addSprite("Z", SOURCE_NAME, new Region(200, 0, 8, 8));
        spritesRepository.addSprite("(", SOURCE_NAME, new Region(208, 0, 8, 8));
        spritesRepository.addSprite(")", SOURCE_NAME, new Region(216, 0, 8, 8));
        spritesRepository.addSprite(":", SOURCE_NAME, new Region(224, 0, 8, 8));
        spritesRepository.addSprite(";", SOURCE_NAME, new Region(232, 0, 8, 8));
        spritesRepository.addSprite("[", SOURCE_NAME, new Region(240, 0, 8, 8));
        spritesRepository.addSprite("]", SOURCE_NAME, new Region(248, 0, 8, 8));
        spritesRepository.addSprite("a", SOURCE_NAME, new Region(0, 8, 8, 8));
        spritesRepository.addSprite("b", SOURCE_NAME, new Region(8, 8, 8, 8));
        spritesRepository.addSprite("c", SOURCE_NAME, new Region(16, 8, 8, 8));
        spritesRepository.addSprite("d", SOURCE_NAME, new Region(24, 8, 8, 8));
        spritesRepository.addSprite("e", SOURCE_NAME, new Region(32, 8, 8, 8));
        spritesRepository.addSprite("f", SOURCE_NAME, new Region(40, 8, 8, 8));
        spritesRepository.addSprite("g", SOURCE_NAME, new Region(48, 8, 8, 8));
        spritesRepository.addSprite("h", SOURCE_NAME, new Region(56, 8, 8, 8));
        spritesRepository.addSprite("i", SOURCE_NAME, new Region(64, 8, 8, 8));
        spritesRepository.addSprite("j", SOURCE_NAME, new Region(72, 8, 8, 8));
        spritesRepository.addSprite("k", SOURCE_NAME, new Region(80, 8, 8, 8));
        spritesRepository.addSprite("l", SOURCE_NAME, new Region(88, 8, 8, 8));
        spritesRepository.addSprite("m", SOURCE_NAME, new Region(96, 8, 8, 8));
        spritesRepository.addSprite("n", SOURCE_NAME, new Region(104, 8, 8, 8));
        spritesRepository.addSprite("o", SOURCE_NAME, new Region(112, 8, 8, 8));
        spritesRepository.addSprite("p", SOURCE_NAME, new Region(120, 8, 8, 8));
        spritesRepository.addSprite("q", SOURCE_NAME, new Region(128, 8, 8, 8));
        spritesRepository.addSprite("r", SOURCE_NAME, new Region(136, 8, 8, 8));
        spritesRepository.addSprite("s", SOURCE_NAME, new Region(144, 8, 8, 8));
        spritesRepository.addSprite("t", SOURCE_NAME, new Region(152, 8, 8, 8));
        spritesRepository.addSprite("u", SOURCE_NAME, new Region(160, 8, 8, 8));
        spritesRepository.addSprite("v", SOURCE_NAME, new Region(168, 8, 8, 8));
        spritesRepository.addSprite("w", SOURCE_NAME, new Region(176, 8, 8, 8));
        spritesRepository.addSprite("x", SOURCE_NAME, new Region(184, 8, 8, 8));
        spritesRepository.addSprite("y", SOURCE_NAME, new Region(192, 8, 8, 8));
        spritesRepository.addSprite("z", SOURCE_NAME, new Region(200, 8, 8, 8));
        spritesRepository.addSprite("\'", SOURCE_NAME, new Region(208, 8, 8, 8));
        spritesRepository.addSprite("PK", SOURCE_NAME, new Region(216, 8, 8, 8));
        spritesRepository.addSprite("MN", SOURCE_NAME, new Region(224, 8, 8, 8));
        spritesRepository.addSprite("-", SOURCE_NAME, new Region(232, 8, 8, 8));
        spritesRepository.addSprite("?", SOURCE_NAME, new Region(240, 8, 8, 8));
        spritesRepository.addSprite("!", SOURCE_NAME, new Region(248, 8, 8, 8));
        spritesRepository.addSprite("0", SOURCE_NAME, new Region(0, 16, 8, 8));
        spritesRepository.addSprite("1", SOURCE_NAME, new Region(8, 16, 8, 8));
        spritesRepository.addSprite("2", SOURCE_NAME, new Region(16, 16, 8, 8));
        spritesRepository.addSprite("3", SOURCE_NAME, new Region(24, 16, 8, 8));
        spritesRepository.addSprite("4", SOURCE_NAME, new Region(32, 16, 8, 8));
        spritesRepository.addSprite("5", SOURCE_NAME, new Region(40, 16, 8, 8));
        spritesRepository.addSprite("6", SOURCE_NAME, new Region(48, 16, 8, 8));
        spritesRepository.addSprite("7", SOURCE_NAME, new Region(56, 16, 8, 8));
        spritesRepository.addSprite("8", SOURCE_NAME, new Region(64, 16, 8, 8));
        spritesRepository.addSprite("9", SOURCE_NAME, new Region(72, 16, 8, 8));
        spritesRepository.addSprite(".", SOURCE_NAME, new Region(80, 16, 8, 8));
        spritesRepository.addSprite("/", SOURCE_NAME, new Region(88, 16, 8, 8));
        spritesRepository.addSprite(",", SOURCE_NAME, new Region(96, 16, 8, 8));
        spritesRepository.addSprite("»", SOURCE_NAME, new Region(104, 16, 8, 8));
        spritesRepository.addSprite("→", SOURCE_NAME, new Region(112, 16, 8, 8));
        spritesRepository.addSprite("↓", SOURCE_NAME, new Region(120, 16, 8, 8));
        spritesRepository.addSprite("$", SOURCE_NAME, new Region(144, 16, 8, 8));
        spritesRepository.addSprite("×", SOURCE_NAME, new Region(152, 16, 8, 8));
        spritesRepository.addSprite("°", SOURCE_NAME, new Region(160, 16, 8, 8));
        spritesRepository.addSprite("&", SOURCE_NAME, new Region(168, 16, 8, 8));
        spritesRepository.addSprite(" ", SOURCE_NAME, new Region(248, 24, 8, 8));
        spritesRepository.addSprite("frame-top-left", SOURCE_NAME, new Region(0, 24, 8, 8));
        spritesRepository.addSprite("frame-top-right", SOURCE_NAME, new Region(8, 24, 8, 8));
        spritesRepository.addSprite("frame-bottom-left", SOURCE_NAME, new Region(16, 24, 8, 8));
        spritesRepository.addSprite("frame-bottom-right", SOURCE_NAME, new Region(24, 24, 8, 8));
        spritesRepository.addSprite("frame-top", SOURCE_NAME, new Region(32, 24, 8, 8));
        spritesRepository.addSprite("frame-bottom", SOURCE_NAME, new Region(40, 24, 8, 8));
        spritesRepository.addSprite("frame-left", SOURCE_NAME, new Region(48, 24, 8, 8));
        spritesRepository.addSprite("frame-right", SOURCE_NAME, new Region(56, 24, 8, 8));
    }
}
