package dev.deadc0de.cobalt;

import dev.deadc0de.cobalt.geometry.Dimension;
import dev.deadc0de.cobalt.geometry.Point;
import dev.deadc0de.cobalt.geometry.Region;
import dev.deadc0de.cobalt.graphics.SpritesRepository;

public class Text {

    private static final String SOURCE_NAME = "text";
    private static final String SPRITES_SOURCE = "/dev/deadc0de/cobalt/images/text.png";
    private static final String BACKGROUND_NAME = "text-background";
    private static final String BACKGROUND_SOURCE = "/dev/deadc0de/cobalt/images/text_background.png";

    public static void addSprites(SpritesRepository<?> spritesRepository) {
        spritesRepository.addSource(BACKGROUND_NAME, BACKGROUND_SOURCE);
        spritesRepository.addSource(SOURCE_NAME, SPRITES_SOURCE);
        spritesRepository.addSprite("A", SOURCE_NAME, new Region(new Point(0, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("B", SOURCE_NAME, new Region(new Point(8, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("C", SOURCE_NAME, new Region(new Point(16, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("D", SOURCE_NAME, new Region(new Point(24, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("E", SOURCE_NAME, new Region(new Point(32, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("F", SOURCE_NAME, new Region(new Point(40, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("G", SOURCE_NAME, new Region(new Point(48, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("H", SOURCE_NAME, new Region(new Point(56, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("I", SOURCE_NAME, new Region(new Point(64, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("J", SOURCE_NAME, new Region(new Point(72, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("K", SOURCE_NAME, new Region(new Point(80, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("L", SOURCE_NAME, new Region(new Point(88, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("M", SOURCE_NAME, new Region(new Point(96, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("N", SOURCE_NAME, new Region(new Point(104, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("O", SOURCE_NAME, new Region(new Point(112, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("P", SOURCE_NAME, new Region(new Point(120, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("Q", SOURCE_NAME, new Region(new Point(128, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("R", SOURCE_NAME, new Region(new Point(136, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("S", SOURCE_NAME, new Region(new Point(144, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("T", SOURCE_NAME, new Region(new Point(152, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("U", SOURCE_NAME, new Region(new Point(160, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("V", SOURCE_NAME, new Region(new Point(168, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("W", SOURCE_NAME, new Region(new Point(176, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("X", SOURCE_NAME, new Region(new Point(184, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("Y", SOURCE_NAME, new Region(new Point(192, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("Z", SOURCE_NAME, new Region(new Point(200, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("(", SOURCE_NAME, new Region(new Point(208, 0), new Dimension(8, 8)));
        spritesRepository.addSprite(")", SOURCE_NAME, new Region(new Point(216, 0), new Dimension(8, 8)));
        spritesRepository.addSprite(":", SOURCE_NAME, new Region(new Point(224, 0), new Dimension(8, 8)));
        spritesRepository.addSprite(";", SOURCE_NAME, new Region(new Point(232, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("[", SOURCE_NAME, new Region(new Point(240, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("]", SOURCE_NAME, new Region(new Point(248, 0), new Dimension(8, 8)));
        spritesRepository.addSprite("a", SOURCE_NAME, new Region(new Point(0, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("b", SOURCE_NAME, new Region(new Point(8, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("c", SOURCE_NAME, new Region(new Point(16, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("d", SOURCE_NAME, new Region(new Point(24, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("e", SOURCE_NAME, new Region(new Point(32, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("f", SOURCE_NAME, new Region(new Point(40, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("g", SOURCE_NAME, new Region(new Point(48, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("h", SOURCE_NAME, new Region(new Point(56, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("i", SOURCE_NAME, new Region(new Point(64, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("j", SOURCE_NAME, new Region(new Point(72, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("k", SOURCE_NAME, new Region(new Point(80, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("l", SOURCE_NAME, new Region(new Point(88, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("m", SOURCE_NAME, new Region(new Point(96, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("n", SOURCE_NAME, new Region(new Point(104, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("o", SOURCE_NAME, new Region(new Point(112, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("p", SOURCE_NAME, new Region(new Point(120, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("q", SOURCE_NAME, new Region(new Point(128, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("r", SOURCE_NAME, new Region(new Point(136, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("s", SOURCE_NAME, new Region(new Point(144, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("t", SOURCE_NAME, new Region(new Point(152, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("u", SOURCE_NAME, new Region(new Point(160, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("v", SOURCE_NAME, new Region(new Point(168, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("w", SOURCE_NAME, new Region(new Point(176, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("x", SOURCE_NAME, new Region(new Point(184, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("y", SOURCE_NAME, new Region(new Point(192, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("z", SOURCE_NAME, new Region(new Point(200, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("\'", SOURCE_NAME, new Region(new Point(208, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("PK", SOURCE_NAME, new Region(new Point(216, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("MN", SOURCE_NAME, new Region(new Point(224, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("-", SOURCE_NAME, new Region(new Point(232, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("?", SOURCE_NAME, new Region(new Point(240, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("!", SOURCE_NAME, new Region(new Point(248, 8), new Dimension(8, 8)));
        spritesRepository.addSprite("0", SOURCE_NAME, new Region(new Point(0, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("1", SOURCE_NAME, new Region(new Point(8, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("2", SOURCE_NAME, new Region(new Point(16, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("3", SOURCE_NAME, new Region(new Point(24, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("4", SOURCE_NAME, new Region(new Point(32, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("5", SOURCE_NAME, new Region(new Point(40, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("6", SOURCE_NAME, new Region(new Point(48, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("7", SOURCE_NAME, new Region(new Point(56, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("8", SOURCE_NAME, new Region(new Point(64, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("9", SOURCE_NAME, new Region(new Point(72, 16), new Dimension(8, 8)));
        spritesRepository.addSprite(".", SOURCE_NAME, new Region(new Point(80, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("/", SOURCE_NAME, new Region(new Point(88, 16), new Dimension(8, 8)));
        spritesRepository.addSprite(",", SOURCE_NAME, new Region(new Point(96, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("»", SOURCE_NAME, new Region(new Point(104, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("→", SOURCE_NAME, new Region(new Point(112, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("↓", SOURCE_NAME, new Region(new Point(120, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("$", SOURCE_NAME, new Region(new Point(144, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("×", SOURCE_NAME, new Region(new Point(152, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("°", SOURCE_NAME, new Region(new Point(160, 16), new Dimension(8, 8)));
        spritesRepository.addSprite("&", SOURCE_NAME, new Region(new Point(168, 16), new Dimension(8, 8)));
        spritesRepository.addSprite(" ", SOURCE_NAME, new Region(new Point(248, 24), new Dimension(8, 8)));
    }
}
